### ISSUE TITLE
Sprites are getting a border

### ISSUE THREAD

**Issue by rmevans1** [Ensighten/grunt-spritesmith#153]
When I generate the sprite sheet I am getting a border around the image

**Comment by twolfson** [comment]
Can you provide an example of what you are seeing?

**Comment by twolfson** [comment]
Closing due to 1 month of inactivity

**Comment by oneHappyCanuck** [comment]
Seeing this as well when using img tag; one on the left is img with sprite class; right is img with src.

![image](https://cloud.githubusercontent.com/assets/375053/13557132/c452ffd6-e3a6-11e5-9e48-bfa9f6b3b708.png)

The generated css has the correct width and height and the generated .png sprites file doesn't show any border. 

.icon-google-drive-transparent {
  background-image: url(../img/sprites.png);
  background-position: -919px -133px;
  width: 30px;
  height: 24px;
}

**Comment by twolfson** [comment]
Can you upload a gist with example HTML and the generated CSS (preferably only the sprite CSS) so we can reproduce the issue?

**Comment by ikosen** [comment]
I am getting the same issue @rmevans1 @oneHappyCanuck any luck fixing this?

**Comment by twolfson** [comment]
@ikosen Can you provide examples of what you are seeing?

**Comment by ikosen** [comment]
![screen shot 2016-03-17 at 6 26 33 pm](https://cloud.githubusercontent.com/assets/12391302/13851176/3125283a-ec6e-11e5-8d1e-2ae1dc4fafc7.png)
![emrspritesheet](https://cloud.githubusercontent.com/assets/12391302/13851182/374cb912-ec6e-11e5-925f-c3e68adf9fcc.png)

code:

``` javascript
sprite:{
            all: {
                src: "path/*.png",
                dest: "path/spritesheet.png",
                destCss: "path/css/sprites.css",
                imgPath: "../assets/img/spritesheet.png"
            }
        }

```

**Comment by twolfson** [comment]
Can you upload the HTML/CSS of the page that's being used on?

**Comment by ikosen** [comment]
The css is really huge and in one file. 17,000 lines. I have removed all the css apart from the one above and this is what I get
![screen shot 2016-03-17 at 7 15 15 pm](https://cloud.githubusercontent.com/assets/12391302/13852775/c2dfb8ca-ec74-11e5-8255-36b3dfdf19ef.png)

**Comment by twolfson** [comment]
Hmm, maybe it's default CSS in Safari. What does it look like in other browsers?

**Comment by ikosen** [comment]
it looks the same on Chrome.
![screen shot 2016-03-17 at 7 21 59 pm](https://cloud.githubusercontent.com/assets/12391302/13852953/a0f09e86-ec75-11e5-8aa3-072696443742.png)

**Comment by ikosen** [comment]
The weird thing is that when I add a border it goes around that one. 
![screen shot 2016-03-17 at 7 26 53 pm](https://cloud.githubusercontent.com/assets/12391302/13853105/3eca46c0-ec76-11e5-93d5-7d418e94ae5f.png)

**Comment by twolfson** [comment]
What's the HTML you are using for the image?

**Comment by ikosen** [comment]
``` html 

<!DOCTYPE html>

<html>

    <head>
        <title>Hello</title>
        <style>

            .icon-Mushroom2 {
              background-image: url(emrspritesheet.png);
              background-position: 0px 0px;
              width: 700px;
              height: 700px;
            }
            .icon-banana_PNG842 {
              background-image: url(emrspritesheet.png);
              background-position: -700px 0px;
              width: 512px;
              height: 512px;
            }
            .icon-blue_guy {
              background-image: url(emrspritesheet.png);
              background-position: 0px -700px;
              width: 500px;
              height: 500px;
            }

        </style>
    </head>

    <body>
        <img class="icon-banana_PNG842">
    </body>

</html>
```

**Comment by twolfson** [comment]
Alright, I have reproduced the error. I tried to remedy it with `border: 0` and `normalize.css` but neither worked.

https://gist.github.com/twolfson/eb4dec3e04ba7bcc006a

The border seems to appear only on `img` tags in Chrome. In Firefox, it's fine in all scenarios. In Chrome, if we do a `div` with `display: inline-block`, then it only shows the border on the `img`.

I think the ideal solution is to remove documentation for `<img>` so people stop using it. If they need `display: inline-block`, then they can roll their own solution (e.g. `.icon` class, `[class^=icon-]` selector).

**Comment by ikosen** [comment]
Thank you. I'll stick to divs myself for the time being. If I can help in anyway let me. I'll be happy to assist

**Comment by twolfson** [comment]
This has been resolved in `spritesheet-templates@10.1.1`, `grunt-spritesmith@6.3.1`, and `gulp.spritesmith@6.2.1`. Thanks again for the bug report =)

**Comment by lb021** [comment]
Hi there,
I still have the exactly same problem with border when using <img> and I'm using version gulp.spritesmith@6.2.1
![screen shot 2016-06-24 at 4 03 17 pm](https://cloud.githubusercontent.com/assets/8493970/16339904/77b39f2a-3a25-11e6-8ac5-12ee8d4dae31.png)
![screen shot 2016-06-24 at 4 03 39 pm](https://cloud.githubusercontent.com/assets/8493970/16339909/7ced12e6-3a25-11e6-83f7-fb892221ed5d.png)

You can check my setup and everything about the project here: https://github.com/lb021/green-unity

**Comment by ikosen** [comment]
@lb021 try using `<div class="icon-luke></div>` instead of the img tag

**Comment by lb021** [comment]
Yeah I did, also need to add property display: inline-block
Was just referring to @twolfson because he said the bug is fixed in this version, maybe he overlooked something here :)

**Comment by ikosen** [comment]
@lb021 my bad. 😄

**Comment by twolfson** [comment]
It's not specifically a `spritesmith` problem, more of documentation in the generated CSS. We did update the documentation in `spritesheet-templates@10.1.1` to no longer mention using the `img` tag:

https://github.com/twolfson/spritesheet-templates/blob/10.1.4/lib/templates/scss.template.handlebars#L47-L72
